version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql://root:password@db/africcase_db
    depends_on:
      - db
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./static/profile_pics:/app/static/profile_pics
      - ./backups:/app/backups

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=africcase_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: