version: '3.8'

services:
  data-fetch:
    build: ./data-fetch-container
    image: candace352/data-fetch:latest
    container_name: data-fetch
    restart: always
    depends_on:
      - redis
      - mysql

  data-process:
    build: ./data-process-container
    image: candace352/data-process:latest
    container_name: data-process
    restart: always
    depends_on:
      - redis
      - mysql

  data-aggregator:
    build: ./data-aggregator-container
    image: candace352/data-aggregator:latest
    container_name: data-aggregator
    restart: always

  monitoring:
    build: ./monitoring-container
    image: candace352/monitoring:latest
    container_name: monitoring
    restart: always
    depends_on:
      - prometheus
      - grafana

  visualization:
    build: ./visualization-container
    image: candace352/visualization:latest
    container_name: visualization
    restart: always

  ml-model:
    build: ./ml-model-container
    image: candace352/ml-model:latest
    container_name: ml-model
    restart: always

  flask-app:
    build: ./waterapp  
    image: candace352/main:latest
    container_name: main
    ports:
      - "5000:5000"  
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:
