runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  FLASK_ENV: "production"
  DATABASE_URL: "mysql+mysqldb://root:@/art_showcase?unix_socket=/cloudsql/YOUR_CONNECTION_NAME"
  
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Set environment variables (modify as needed)
ENV FLASK_APP=app.py
ENV FLASK_ENV=production

# Run the application
CMD ["python", "app.py"]
